/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JFrame;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import sistemarodoviario.*;
import sistemarodoviario.jpa.Pedido;
import javax.swing.JOptionPane;
import org.apache.taglibs.standard.lang.jstl.PlusOperator;

/**
 *
 * @author Marcelo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPassagem = new javax.swing.JPanel();
        jPanelPassagem.setVisible(false);
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numeroDoPedidoTextField = new javax.swing.JTextField();
        cpfPassageiroTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nomePassageiroTextField = new javax.swing.JTextField();
        jLabelPassagemResult = new javax.swing.JLabel();
        retirarPassagemjButton = new javax.swing.JButton();
        jPanelImprimirPassagem = new javax.swing.JPanel();
        jPanelImprimirPassagem.setVisible(false);
        ImprimirjButton = new javax.swing.JButton();
        ImprimirjButton.addActionListener(new ActionPrintTicketWindow());
        numeroDoPedidoText = new javax.swing.JLabel();
        numeroDoPedidoResult = new javax.swing.JLabel();
        nomeDoPassageiroText = new javax.swing.JLabel();
        nomeDoPassageiroResult = new javax.swing.JLabel();
        cpfDoPassagemText = new javax.swing.JLabel();
        cpfDoPassageiroResult = new javax.swing.JLabel();
        dataIdaPassagemText = new javax.swing.JLabel();
        dataInicioPassagemResult = new javax.swing.JLabel();
        dataFimPassagemText = new javax.swing.JLabel();
        dataFimPassagemResult = new javax.swing.JLabel();
        cidadeOrigemPassagemText = new javax.swing.JLabel();
        cidadeOrigemResult = new javax.swing.JLabel();
        cidadeDestinoPassagemText = new javax.swing.JLabel();
        cidadeDestinoResult = new javax.swing.JLabel();
        jPanelPagamento = new javax.swing.JPanel();
        jPanelPagamento.setVisible(false);
        EfetuarPagamentojButton = new javax.swing.JButton();
        numeroDoPedidoText2 = new javax.swing.JLabel();
        numeroDoPedidoASerPagojTextField = new javax.swing.JTextField();
        efetuarPagamentoLabel = new javax.swing.JLabel();
        jLabelPagarResult = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        HomeMenu = new javax.swing.JMenu();
        Logout = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenuItem();
        PassagemMenu = new javax.swing.JMenu();
        RetirarPassagemMenuItem = new javax.swing.JMenuItem();
        RetirarPassagemMenuItem.addActionListener(new ActionOpenPassagemWindow());
        EfetuarPagamentoItemMenu = new javax.swing.JMenuItem();
        EfetuarPagamentoItemMenu.addActionListener(new ActionOpenPayWindow());
        AjudaMenu = new javax.swing.JMenu();
        SobreMenuItem = new javax.swing.JMenuItem();
        SobreMenuItem.addActionListener(new ActionOpenAboutWindow());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Rodoviario");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanelPassagem.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nome do Passageiro:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("CPF do Passageiro:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setText("Retirar Passagem");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Número do Pedido:");

        retirarPassagemjButton.setText("Retirar Passagem");
        retirarPassagemjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarPassagemjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPassagemLayout = new javax.swing.GroupLayout(jPanelPassagem);
        jPanelPassagem.setLayout(jPanelPassagemLayout);
        jPanelPassagemLayout.setHorizontalGroup(
            jPanelPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPassagemLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(jPanelPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(jPanelPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPassagemResult, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfPassageiroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomePassageiroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(numeroDoPedidoTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(retirarPassagemjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(227, 227, 227))
        );
        jPanelPassagemLayout.setVerticalGroup(
            jPanelPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPassagemLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel7)
                .addGap(37, 37, 37)
                .addGroup(jPanelPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroDoPedidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25)
                .addGroup(jPanelPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomePassageiroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cpfPassageiroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(retirarPassagemjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(jLabelPassagemResult, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(485, Short.MAX_VALUE))
        );

        jPanelImprimirPassagem.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        ImprimirjButton.setBackground(new java.awt.Color(255, 255, 255));
        ImprimirjButton.setText("Imprimir");

        numeroDoPedidoText.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        numeroDoPedidoText.setText("Número do Pedido:");

        numeroDoPedidoResult.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        nomeDoPassageiroText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nomeDoPassageiroText.setText("Nome do Passageiro:");

        nomeDoPassageiroResult.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        cpfDoPassagemText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cpfDoPassagemText.setText("CPF do Passageiro:");

        cpfDoPassageiroResult.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        dataIdaPassagemText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dataIdaPassagemText.setText("Data Inicio da Passagem:");

        dataInicioPassagemResult.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        dataFimPassagemText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dataFimPassagemText.setText("Data Fim da Passagem:");

        dataFimPassagemResult.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        cidadeOrigemPassagemText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cidadeOrigemPassagemText.setText("Cidade Origem:");

        cidadeOrigemResult.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        cidadeDestinoPassagemText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cidadeDestinoPassagemText.setText("Cidade Destino:");

        cidadeDestinoResult.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanelImprimirPassagemLayout = new javax.swing.GroupLayout(jPanelImprimirPassagem);
        jPanelImprimirPassagem.setLayout(jPanelImprimirPassagemLayout);
        jPanelImprimirPassagemLayout.setHorizontalGroup(
            jPanelImprimirPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelImprimirPassagemLayout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addGroup(jPanelImprimirPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelImprimirPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelImprimirPassagemLayout.createSequentialGroup()
                            .addComponent(cpfDoPassagemText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cpfDoPassageiroResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelImprimirPassagemLayout.createSequentialGroup()
                            .addComponent(nomeDoPassageiroText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nomeDoPassageiroResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelImprimirPassagemLayout.createSequentialGroup()
                            .addComponent(numeroDoPedidoText)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numeroDoPedidoResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelImprimirPassagemLayout.createSequentialGroup()
                            .addGroup(jPanelImprimirPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dataFimPassagemText, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dataIdaPassagemText))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelImprimirPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dataInicioPassagemResult, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dataFimPassagemResult, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)))
                        .addGroup(jPanelImprimirPassagemLayout.createSequentialGroup()
                            .addGroup(jPanelImprimirPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cidadeOrigemPassagemText, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cidadeDestinoPassagemText, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanelImprimirPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cidadeDestinoResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cidadeOrigemResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(ImprimirjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(316, 316, 316))
        );
        jPanelImprimirPassagemLayout.setVerticalGroup(
            jPanelImprimirPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImprimirPassagemLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(jPanelImprimirPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numeroDoPedidoText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numeroDoPedidoResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanelImprimirPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomeDoPassageiroText)
                    .addComponent(nomeDoPassageiroResult, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelImprimirPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpfDoPassageiroResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfDoPassagemText))
                .addGap(18, 18, 18)
                .addGroup(jPanelImprimirPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dataInicioPassagemResult, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataIdaPassagemText))
                .addGap(25, 25, 25)
                .addGroup(jPanelImprimirPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dataFimPassagemText)
                    .addComponent(dataFimPassagemResult, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanelImprimirPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cidadeOrigemResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cidadeOrigemPassagemText, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelImprimirPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cidadeDestinoResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cidadeDestinoPassagemText, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(ImprimirjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(420, Short.MAX_VALUE))
        );

        EfetuarPagamentojButton.setText("Pagar");
        EfetuarPagamentojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EfetuarPagamentojButtonActionPerformed(evt);
            }
        });

        numeroDoPedidoText2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        numeroDoPedidoText2.setText("Número do Pedido:");

        efetuarPagamentoLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        efetuarPagamentoLabel.setText("Efetuar pagamento de passagem:");

        javax.swing.GroupLayout jPanelPagamentoLayout = new javax.swing.GroupLayout(jPanelPagamento);
        jPanelPagamento.setLayout(jPanelPagamentoLayout);
        jPanelPagamentoLayout.setHorizontalGroup(
            jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPagamentoLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(efetuarPagamentoLabel)
                    .addGroup(jPanelPagamentoLayout.createSequentialGroup()
                        .addComponent(numeroDoPedidoText2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numeroDoPedidoASerPagojTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(EfetuarPagamentojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPagarResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(134, 134, 134))
        );
        jPanelPagamentoLayout.setVerticalGroup(
            jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPagamentoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(efetuarPagamentoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addGroup(jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numeroDoPedidoText2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numeroDoPedidoASerPagojTextField))
                .addGap(26, 26, 26)
                .addComponent(EfetuarPagamentojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabelPagarResult, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Docs/LogoFCI.png"))); // NOI18N

        HomeMenu.setText("Home");

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        HomeMenu.add(Logout);

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        HomeMenu.add(Sair);

        jMenuBar1.add(HomeMenu);

        PassagemMenu.setText("Passagem");

        RetirarPassagemMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        RetirarPassagemMenuItem.setText("Retirar Passagem");
        PassagemMenu.add(RetirarPassagemMenuItem);

        EfetuarPagamentoItemMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        EfetuarPagamentoItemMenu.setText("Efetuar Pagamento");
        PassagemMenu.add(EfetuarPagamentoItemMenu);

        jMenuBar1.add(PassagemMenu);

        AjudaMenu.setText("Ajuda");

        SobreMenuItem.setText("Sobre ...");
        AjudaMenu.add(SobreMenuItem);

        jMenuBar1.add(AjudaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jPanelImprimirPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(332, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 375, Short.MAX_VALUE)
                    .addComponent(jPanelPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 374, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelPassagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 882, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jPanelImprimirPassagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(24, 24, 24)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 256, Short.MAX_VALUE)
                    .addComponent(jPanelPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 256, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_SairActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        Login tela = new Login();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void retirarPassagemjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarPassagemjButtonActionPerformed
        Pedido pAtual = null;
        PedidoSessionBeanRemote beanPedido;
        try {

            beanPedido = (PedidoSessionBeanRemote) sistemarodoviariodesktop.ServiceLocator.buscarEJB(PedidoSessionBeanRemote.class);


            String numeroDoPedido = numeroDoPedidoTextField.getText();
            String nomePassageiro = nomePassageiroTextField.getText();
            String cpfPassageiro = cpfPassageiroTextField.getText();

            if ("".equals(numeroDoPedido) || "".equals(nomePassageiro) || "".equals(cpfPassageiro)) {
                jLabelPassagemResult.setText("Preencha todos os dados, pois são necessários.");
            } else {
                pAtual = beanPedido.recebePedidoPorID(Long.parseLong(numeroDoPedidoTextField.getText()));
            }

            if (pAtual != null) {
                if (!nomePassageiro.equals(pAtual.getNomePassageiro())) {
                    jLabelPassagemResult.setText("Nome do Passageiro incorreto.");
                } else if (!cpfPassageiro.equals(pAtual.getCpfPassageiro())) {
                    jLabelPassagemResult.setText("CPF do Passageiro incorreto.");
                } else {
                    if (pAtual.isPagoCompra()) {
                        numeroDoPedidoResult.setText(pAtual.getId().toString());
                        nomeDoPassageiroResult.setText(pAtual.getNomePassageiro());
                        cpfDoPassageiroResult.setText(pAtual.getCpfPassageiro());
                        dataInicioPassagemResult.setText(pAtual.getViagem().getTrajeto().getDataInicioViagem());
                        dataFimPassagemResult.setText(pAtual.getViagem().getTrajeto().getDataFimViagem());
                        cidadeOrigemResult.setText(pAtual.getViagem().getTrajeto().getCidadeOrigem().getNomeCidade());
                        cidadeDestinoResult.setText(pAtual.getViagem().getTrajeto().getCidadeDestino().getNomeCidade());
                        jPanelPassagem.setVisible(false);
                        jPanelImprimirPassagem.setVisible(true);
                        validate();
                    } else {
                        jLabelPassagemResult.setText("A passagem não foi paga.");
                    }
                }

            } else {
                jLabelPassagemResult.setText("Pedido não encontrado");
            }
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_retirarPassagemjButtonActionPerformed

    private void EfetuarPagamentojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EfetuarPagamentojButtonActionPerformed
        // TODO add your handling code here:
        Pedido pASerPago = null;
        PedidoSessionBeanRemote beanPedido;
        try {

            beanPedido = (PedidoSessionBeanRemote) sistemarodoviariodesktop.ServiceLocator.buscarEJB(PedidoSessionBeanRemote.class);


            String numeroDoPedidoASerPago = numeroDoPedidoASerPagojTextField.getText();

            if ("".equals(numeroDoPedidoASerPago)) {
                jLabelPassagemResult.setText("Preencha o número do pedido.");
            } else {
                pASerPago = beanPedido.recebePedidoPorID(Long.parseLong(numeroDoPedidoASerPagojTextField.getText()));
            }

            if (pASerPago != null) {

                if (pASerPago.isPagoCompra()) {
                    jLabelPagarResult.setText("Passagem já foi paga.");
                } else {
                    pASerPago.setPagoCompra(true);
                    beanPedido.salvar(pASerPago);
                    jLabelPagarResult.setText("Pago.");
                }
            } else {
                jLabelPagarResult.setText("Pedido não encontrado");
            }
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }


        
        
        
    }//GEN-LAST:event_EfetuarPagamentojButtonActionPerformed

    
    
    
    
    
    
    
    
    private class ActionOpenPassagemWindow implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            jPanelImprimirPassagem.setVisible(false);
            jPanelPagamento.setVisible(false);
            jPanelPassagem.setVisible(true);
            validate();

        }
    }

    private class ActionOpenPayWindow implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            jPanelPassagem.setVisible(false);
            jPanelImprimirPassagem.setVisible(false);
            jPanelPagamento.setVisible(true);
            validate();
        }
    }

    private class ActionOpenAboutWindow implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Sobre sobre = new Sobre();
            sobre.setVisible(true);
            validate();
        }
    }

    private class ActionOpenTicketWindow implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
        }
    }

    private class ActionPrintTicketWindow implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            JOptionPane.showMessageDialog(null, "Ticket Impresso!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AjudaMenu;
    private javax.swing.JMenuItem EfetuarPagamentoItemMenu;
    private javax.swing.JButton EfetuarPagamentojButton;
    private javax.swing.JMenu HomeMenu;
    private javax.swing.JButton ImprimirjButton;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenu PassagemMenu;
    private javax.swing.JMenuItem RetirarPassagemMenuItem;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenuItem SobreMenuItem;
    private javax.swing.JLabel cidadeDestinoPassagemText;
    private javax.swing.JLabel cidadeDestinoResult;
    private javax.swing.JLabel cidadeOrigemPassagemText;
    private javax.swing.JLabel cidadeOrigemResult;
    private javax.swing.JLabel cpfDoPassageiroResult;
    private javax.swing.JLabel cpfDoPassagemText;
    private javax.swing.JTextField cpfPassageiroTextField;
    private javax.swing.JLabel dataFimPassagemResult;
    private javax.swing.JLabel dataFimPassagemText;
    private javax.swing.JLabel dataIdaPassagemText;
    private javax.swing.JLabel dataInicioPassagemResult;
    private javax.swing.JLabel efetuarPagamentoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelPagarResult;
    private javax.swing.JLabel jLabelPassagemResult;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelImprimirPassagem;
    private javax.swing.JPanel jPanelPagamento;
    private javax.swing.JPanel jPanelPassagem;
    private javax.swing.JLabel nomeDoPassageiroResult;
    private javax.swing.JLabel nomeDoPassageiroText;
    private javax.swing.JTextField nomePassageiroTextField;
    private javax.swing.JTextField numeroDoPedidoASerPagojTextField;
    private javax.swing.JLabel numeroDoPedidoResult;
    private javax.swing.JLabel numeroDoPedidoText;
    private javax.swing.JLabel numeroDoPedidoText2;
    private javax.swing.JTextField numeroDoPedidoTextField;
    private javax.swing.JButton retirarPassagemjButton;
    // End of variables declaration//GEN-END:variables
}
