INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (1, 'AC');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (2, 'AL');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (3, 'AP');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (4, 'AM');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (5, 'BA');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (6, 'CE');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (7, 'DF');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (8, 'ES');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (9, 'GO');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (10, 'MA');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (11, 'MG');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (12, 'MS');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (13, 'MG');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (14, 'PA');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (15, 'PB');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (16, 'PR');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (17, 'PE');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (18, 'PI');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (19, 'RJ');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (20, 'RN');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (21, 'RS');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (22, 'RO');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (23, 'RR');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (24, 'SC');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (25, 'SP');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (26, 'SE');
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO) VALUES (27, 'TO');


INSERT INTO CIDADE (ID_CIDADE, NOME_CIDADE,ESTADO_FK) VALUES (1, 'SAO PAULO',25);
INSERT INTO CIDADE (ID_CIDADE, NOME_CIDADE,ESTADO_FK) VALUES (2, 'CAMPINAS',25);
INSERT INTO CIDADE (ID_CIDADE, NOME_CIDADE,ESTADO_FK) VALUES (3, 'SANTOS',25);
INSERT INTO CIDADE (ID_CIDADE, NOME_CIDADE,ESTADO_FK) VALUES (4, 'SOROCABA',25);
INSERT INTO CIDADE (ID_CIDADE, NOME_CIDADE,ESTADO_FK) VALUES (5, 'RIBEIRAO PRETO',25);
INSERT INTO CIDADE (ID_CIDADE, NOME_CIDADE,ESTADO_FK) VALUES (6, 'BELO HORIZONTE',11);
INSERT INTO CIDADE (ID_CIDADE, NOME_CIDADE,ESTADO_FK) VALUES (7, 'CURITIBA',16);
INSERT INTO CIDADE (ID_CIDADE, NOME_CIDADE,ESTADO_FK) VALUES (8, 'RIO DE JANEIRO',19);





