insert into FUNCIONARIO(ID_FUNCIONARIO,USUARIO_FUNC,NOME_FUNC,SENHA_FUNC,EMAIL_FUNC)
values(1,'CALEBE123','CALEBE','123','calebe@mackenzie.com.br');

insert into FUNCIONARIO(ID_FUNCIONARIO,USUARIO_FUNC,NOME_FUNC,SENHA_FUNC,EMAIL_FUNC)
values(2,'MARCELO','MARCELO GRANHA','123','30933714@mackenzie.com.br');

insert into FUNCIONARIO(ID_FUNCIONARIO,USUARIO_FUNC,NOME_FUNC,SENHA_FUNC,EMAIL_FUNC)
values(3,'ANDERSON','ANDERSON MORINO','123','30974917@mackenzie.com.br');

insert into FUNCIONARIO(ID_FUNCIONARIO,USUARIO_FUNC,NOME_FUNC,SENHA_FUNC,EMAIL_FUNC)
values(4,'THIAGO','THIAGO SATO','123','30916240@mackenzie.com.br');

