INSERT INTO ONIBUS (ID_ONIBUS, NOME_EMPRESA,TRAJETO_FK) 
VALUES (1, 'MACKTRANS',1);

INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (1, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (2, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (3, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (4, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (5, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (6, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (7, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (8, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (9, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (10, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (11, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (12, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (13, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (14, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (15, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (16, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (17, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (18, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (19, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (20, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (21, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (22, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (23, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (24, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (25, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (26, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (27, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (28, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (29, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (30, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (31, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (32, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (33, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (34, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (35, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (36, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (37, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (38, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (39, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (40, 'CORREDOR',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (41, 'JANELA',0,1);
INSERT INTO ASSENTO (ID_ASSENTO, LOCAL_ASSENTO,DISPONIBILIDADE,ONIBUS_FK) 
VALUES (42, 'CORREDOR',0,1);

